import { RootFolder } from './clients/localStorageClient';

export const MOCKED_DATA: RootFolder = {
  id: '__root__',
  name: '__root__',
  protectionLevel: 'admin',
  type: 'folder',
  path: '',
  children: {
    '2OZkKhxL': {
      id: '2OZkKhxL',
      name: 'pdq95FcoOXomjmedZCIQ4OFNENWSWsQamC',
      protectionLevel: 'admin',
      type: 'folder',
      path: '2OZkKhxL',
      children: {
        '4fXztf3J': {
          id: '4fXztf3J',
          name: 'B7rD79AtYU5rft2dUfQWvI5oWKylSPEixzC',
          protectionLevel: 'user',
          type: 'file',
          extension: 'svg',
          path: '2OZkKhxL/4fXztf3J',
        },
        '2bLhoqBI': {
          id: '2bLhoqBI',
          name: 'JGuVTFhqTO1dzrOrbVPV1gyeC9VOkhAo',
          protectionLevel: 'user',
          type: 'folder',
          path: '2OZkKhxL/2bLhoqBI',
          children: {
            DLiEwhfN: {
              id: 'DLiEwhfN',
              name: 'zBH94YXDs290RYZCuYU52JingERv3x',
              protectionLevel: 'user',
              type: 'file',
              extension: 'pdf',
              path: '2OZkKhxL/2bLhoqBI/DLiEwhfN',
            },
            gOrL4uGI: {
              id: 'gOrL4uGI',
              name: 'rQqnpwehnZAglR64qgJjyPk2xSJ',
              protectionLevel: 'user',
              type: 'folder',
              path: '2OZkKhxL/2bLhoqBI/gOrL4uGI',
              children: {
                sZgTGkCE: {
                  id: 'sZgTGkCE',
                  name: 'WIgijDoMtjg55U3ZEY6uypbOrvAPn9',
                  protectionLevel: 'admin',
                  type: 'file',
                  extension: 'svg',
                  path: '2OZkKhxL/2bLhoqBI/gOrL4uGI/sZgTGkCE',
                },
                tcpOO4Xs: {
                  id: 'tcpOO4Xs',
                  name: '6CZBRTStjQ8oq9VdUkuBK4Pgm6p3C7YdGzi',
                  protectionLevel: 'admin',
                  type: 'file',
                  extension: 'svg',
                  path: '2OZkKhxL/2bLhoqBI/gOrL4uGI/tcpOO4Xs',
                },
                R2MjM2aG: {
                  id: 'R2MjM2aG',
                  name: '7blgYnXCh4iHvEOG6YuklmLucWD',
                  protectionLevel: 'admin',
                  type: 'folder',
                  path: '2OZkKhxL/2bLhoqBI/gOrL4uGI/R2MjM2aG',
                  children: {
                    siSB2soq: {
                      id: 'siSB2soq',
                      name: '6TO2Zbp7NzLgzRXpp9pwsb16kEBQ1mr2FBS',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2OZkKhxL/2bLhoqBI/gOrL4uGI/R2MjM2aG/siSB2soq',
                      children: {},
                    },
                    SzsWj6zt: {
                      id: 'SzsWj6zt',
                      name: 'FtUZ55ygdEczot3LJGow53HHl54ToWUtIg',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'svg',
                      path: '2OZkKhxL/2bLhoqBI/gOrL4uGI/R2MjM2aG/SzsWj6zt',
                    },
                    B8u5jx2j: {
                      id: 'B8u5jx2j',
                      name: 'nmZYIpQvTBFE638b8kGP1nNlGLBHETSlo',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'svg',
                      path: '2OZkKhxL/2bLhoqBI/gOrL4uGI/R2MjM2aG/B8u5jx2j',
                    },
                    SYB7hpxh: {
                      id: 'SYB7hpxh',
                      name: 'i2h7Kt4kJB5bJVFd6sJmpGVTdgI1p4ueUWP',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2OZkKhxL/2bLhoqBI/gOrL4uGI/R2MjM2aG/SYB7hpxh',
                      children: {},
                    },
                    D4GNkKae: {
                      id: 'D4GNkKae',
                      name: '4R20wP4jwEZggao7n0ycEQQyR1nmAmp',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2OZkKhxL/2bLhoqBI/gOrL4uGI/R2MjM2aG/D4GNkKae',
                      children: {},
                    },
                  },
                },
                U8aIkrwC: {
                  id: 'U8aIkrwC',
                  name: 'bEptgrQAZnpnFLl2W4497LIYTOdm0Nr',
                  protectionLevel: 'user',
                  type: 'file',
                  extension: 'txt',
                  path: '2OZkKhxL/2bLhoqBI/gOrL4uGI/U8aIkrwC',
                },
                lLnUFlVf: {
                  id: 'lLnUFlVf',
                  name: 'y7RcZjV3sRNe1olnrhqTjpiPprh',
                  protectionLevel: 'admin',
                  type: 'folder',
                  path: '2OZkKhxL/2bLhoqBI/gOrL4uGI/lLnUFlVf',
                  children: {
                    Vd5wPFFo: {
                      id: 'Vd5wPFFo',
                      name: '7jRHHuDQcVSuZJdiKPHjauOE7',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'svg',
                      path: '2OZkKhxL/2bLhoqBI/gOrL4uGI/lLnUFlVf/Vd5wPFFo',
                    },
                    JLEpKT1H: {
                      id: 'JLEpKT1H',
                      name: 'ItGSklxVHytm9dpKYwnBfAoNg66UyfC1A',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'svg',
                      path: '2OZkKhxL/2bLhoqBI/gOrL4uGI/lLnUFlVf/JLEpKT1H',
                    },
                    hpD4fmiC: {
                      id: 'hpD4fmiC',
                      name: 'FqJcOfSC2nK83iBVSvY3NXUfqd3z',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'svg',
                      path: '2OZkKhxL/2bLhoqBI/gOrL4uGI/lLnUFlVf/hpD4fmiC',
                    },
                    AlNXFOWD: {
                      id: 'AlNXFOWD',
                      name: '8s0EiwBbifD4msp1cEk9kMntoHpZMa',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'svg',
                      path: '2OZkKhxL/2bLhoqBI/gOrL4uGI/lLnUFlVf/AlNXFOWD',
                    },
                    fykNL3MO: {
                      id: 'fykNL3MO',
                      name: 'ZUvWjys30AtVkZRpnXZiwtoMPcHwN',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'svg',
                      path: '2OZkKhxL/2bLhoqBI/gOrL4uGI/lLnUFlVf/fykNL3MO',
                    },
                  },
                },
              },
            },
            '6GAqqWA0': {
              id: '6GAqqWA0',
              name: 'LDbIig14KchJpKdUqOtup8FPqBAKzS',
              protectionLevel: 'admin',
              type: 'file',
              extension: 'txt',
              path: '2OZkKhxL/2bLhoqBI/6GAqqWA0',
            },
            vJScTV80: {
              id: 'vJScTV80',
              name: 'sSYo1kdwwtyuVNCOA6Pqdic6EMQ0TxN',
              protectionLevel: 'admin',
              type: 'file',
              extension: 'txt',
              path: '2OZkKhxL/2bLhoqBI/vJScTV80',
            },
            F1TLACWM: {
              id: 'F1TLACWM',
              name: 'HCCAjyrwy3BS7x5KQ6z9q9c7SckG',
              protectionLevel: 'admin',
              type: 'file',
              extension: 'txt',
              path: '2OZkKhxL/2bLhoqBI/F1TLACWM',
            },
          },
        },
        XdWkDmxP: {
          id: 'XdWkDmxP',
          name: 'CBopLkfszhz2iS06bM5Dq2zRA',
          protectionLevel: 'admin',
          type: 'file',
          extension: 'txt',
          path: '2OZkKhxL/XdWkDmxP',
        },
        xMJKwa8H: {
          id: 'xMJKwa8H',
          name: 'DAa58hq2xLREvldcz84GMPSatJUwK',
          protectionLevel: 'user',
          type: 'file',
          extension: 'pdf',
          path: '2OZkKhxL/xMJKwa8H',
        },
        PdtJgIoq: {
          id: 'PdtJgIoq',
          name: 'q5C1SwFu8F7LvdnFgUUblRoTeuv9OyXrHB',
          protectionLevel: 'user',
          type: 'folder',
          path: '2OZkKhxL/PdtJgIoq',
          children: {
            Cy2Tth41: {
              id: 'Cy2Tth41',
              name: 'bJFAypWRv63aa6VWqsB5WAS2QsI0',
              protectionLevel: 'user',
              type: 'folder',
              path: '2OZkKhxL/PdtJgIoq/Cy2Tth41',
              children: {
                duxCocCs: {
                  id: 'duxCocCs',
                  name: '4GfCokQmqDE9VrJIC5ZpHfP5hYqDWc',
                  protectionLevel: 'user',
                  type: 'folder',
                  path: '2OZkKhxL/PdtJgIoq/Cy2Tth41/duxCocCs',
                  children: {
                    QSpHaxyU: {
                      id: 'QSpHaxyU',
                      name: 'VFQMaDa4hbpqzydYLjehCFcZFVUm',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'pdf',
                      path: '2OZkKhxL/PdtJgIoq/Cy2Tth41/duxCocCs/QSpHaxyU',
                    },
                    ax6MlsO3: {
                      id: 'ax6MlsO3',
                      name: 'OpUl54TnnhlqiVcLI30I51lYcrNm9T',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/Cy2Tth41/duxCocCs/ax6MlsO3',
                      children: {},
                    },
                    oC0FKPuu: {
                      id: 'oC0FKPuu',
                      name: '75GkZjw7sbNvUNkdWRPhpxidqX7p8R1D',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/Cy2Tth41/duxCocCs/oC0FKPuu',
                      children: {},
                    },
                    '5TEfQUxy': {
                      id: '5TEfQUxy',
                      name: 'ZcgeLQ8L8mFsmL8PKN9TCFEcD',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'pdf',
                      path: '2OZkKhxL/PdtJgIoq/Cy2Tth41/duxCocCs/5TEfQUxy',
                    },
                    TYH2uT5X: {
                      id: 'TYH2uT5X',
                      name: '3lFX97DOW4FoJKiLNjOeE43txKgxahQw42I',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'pdf',
                      path: '2OZkKhxL/PdtJgIoq/Cy2Tth41/duxCocCs/TYH2uT5X',
                    },
                  },
                },
                MNHDwCFc: {
                  id: 'MNHDwCFc',
                  name: 'qHo1LYJllt5sIXC8nUDlPQxZkgDCOGVye',
                  protectionLevel: 'admin',
                  type: 'file',
                  extension: 'txt',
                  path: '2OZkKhxL/PdtJgIoq/Cy2Tth41/MNHDwCFc',
                },
                wSVCLvI8: {
                  id: 'wSVCLvI8',
                  name: 'KL2ghCEmbVueaIiK7CT9XQIGObsYx',
                  protectionLevel: 'admin',
                  type: 'folder',
                  path: '2OZkKhxL/PdtJgIoq/Cy2Tth41/wSVCLvI8',
                  children: {
                    JdSjAeCR: {
                      id: 'JdSjAeCR',
                      name: 'WkNBDkx9HSCg5lOa8XwGz7eNW',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'txt',
                      path: '2OZkKhxL/PdtJgIoq/Cy2Tth41/wSVCLvI8/JdSjAeCR',
                    },
                    '7ywkBIQD': {
                      id: '7ywkBIQD',
                      name: 'ncxS0afnJp7khZVxw1LqACvr9ppgi2',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/Cy2Tth41/wSVCLvI8/7ywkBIQD',
                      children: {},
                    },
                    AnVLUYht: {
                      id: 'AnVLUYht',
                      name: '6DkqvPTmsLJxFLXFerCoj1fk7hpDME4ekat',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'svg',
                      path: '2OZkKhxL/PdtJgIoq/Cy2Tth41/wSVCLvI8/AnVLUYht',
                    },
                    JJ5jwmp8: {
                      id: 'JJ5jwmp8',
                      name: 'hcFaXeOmzN81emUdCrdDHMxxtBGy',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'svg',
                      path: '2OZkKhxL/PdtJgIoq/Cy2Tth41/wSVCLvI8/JJ5jwmp8',
                    },
                    xIfrjYMV: {
                      id: 'xIfrjYMV',
                      name: 'Fvl57f0C9PPtey7iKJmRSsgWBqZpMv',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/Cy2Tth41/wSVCLvI8/xIfrjYMV',
                      children: {},
                    },
                  },
                },
                uQJb4Uvl: {
                  id: 'uQJb4Uvl',
                  name: 'SNIz0cQlFcIfGnlfQ6Kd26vxPWYjJjZ6P',
                  protectionLevel: 'user',
                  type: 'file',
                  extension: 'svg',
                  path: '2OZkKhxL/PdtJgIoq/Cy2Tth41/uQJb4Uvl',
                },
                XTrG6ZKn: {
                  id: 'XTrG6ZKn',
                  name: 'AJi9JQMFspy08b1JqJzxBtL2MzL',
                  protectionLevel: 'admin',
                  type: 'file',
                  extension: 'svg',
                  path: '2OZkKhxL/PdtJgIoq/Cy2Tth41/XTrG6ZKn',
                },
              },
            },
            sye04J7G: {
              id: 'sye04J7G',
              name: 'oWEfIKoY00LHw3jCFkYpGIBpznBDaJHnEt1',
              protectionLevel: 'user',
              type: 'folder',
              path: '2OZkKhxL/PdtJgIoq/sye04J7G',
              children: {
                '6SXAWOpR': {
                  id: '6SXAWOpR',
                  name: 'N7VgzWEvTTGKvIcsMDSwcb7eyhNgHlWkUMt',
                  protectionLevel: 'user',
                  type: 'file',
                  extension: 'svg',
                  path: '2OZkKhxL/PdtJgIoq/sye04J7G/6SXAWOpR',
                },
                bPbDla4H: {
                  id: 'bPbDla4H',
                  name: 'qT52j1pt1sipVxl90GiMfdUpF',
                  protectionLevel: 'admin',
                  type: 'file',
                  extension: 'svg',
                  path: '2OZkKhxL/PdtJgIoq/sye04J7G/bPbDla4H',
                },
                wyyaZYkM: {
                  id: 'wyyaZYkM',
                  name: 'OCOlZuwhaydxrKsSN1HtFiN6t',
                  protectionLevel: 'user',
                  type: 'folder',
                  path: '2OZkKhxL/PdtJgIoq/sye04J7G/wyyaZYkM',
                  children: {
                    '2Z7N8J70': {
                      id: '2Z7N8J70',
                      name: 'O3XTCYL1b3qIPHgfU1CYKmQDwrvDcATWQ',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/sye04J7G/wyyaZYkM/2Z7N8J70',
                      children: {},
                    },
                    bwUQj1qV: {
                      id: 'bwUQj1qV',
                      name: 'tV1MLgkNRfwuiKWnzZKoMFBwh0aZ',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/sye04J7G/wyyaZYkM/bwUQj1qV',
                      children: {},
                    },
                    NmQUhxJn: {
                      id: 'NmQUhxJn',
                      name: 'nDiwgdSI2iXjA0bKYupCEw1hT5urVwJkYnG',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'txt',
                      path: '2OZkKhxL/PdtJgIoq/sye04J7G/wyyaZYkM/NmQUhxJn',
                    },
                    x7O2QSVy: {
                      id: 'x7O2QSVy',
                      name: 'dgiT6iGzr5iig56ItovpnhimMew',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/sye04J7G/wyyaZYkM/x7O2QSVy',
                      children: {},
                    },
                    mZqG7Kwk: {
                      id: 'mZqG7Kwk',
                      name: 'DNU6DwKis57Q8fMn3G7MPV4ubs',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'txt',
                      path: '2OZkKhxL/PdtJgIoq/sye04J7G/wyyaZYkM/mZqG7Kwk',
                    },
                  },
                },
                X2YzwYhB: {
                  id: 'X2YzwYhB',
                  name: 'ANFbdlv7oXlPG1VkqaGT6v8ONfkw6QA',
                  protectionLevel: 'admin',
                  type: 'folder',
                  path: '2OZkKhxL/PdtJgIoq/sye04J7G/X2YzwYhB',
                  children: {
                    a3aA08nZ: {
                      id: 'a3aA08nZ',
                      name: 'StHNWsCdE02RCxMCNjELOpjUeY7PLR3a',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'txt',
                      path: '2OZkKhxL/PdtJgIoq/sye04J7G/X2YzwYhB/a3aA08nZ',
                    },
                    TwjseBVA: {
                      id: 'TwjseBVA',
                      name: 'YS4NUkSMht90GaY1cCkqGbYZP',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'txt',
                      path: '2OZkKhxL/PdtJgIoq/sye04J7G/X2YzwYhB/TwjseBVA',
                    },
                    HdsoPW8k: {
                      id: 'HdsoPW8k',
                      name: 'yKmDJpGiaF1QQGIr0YnXJgZ1nz1KeRNAH',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/sye04J7G/X2YzwYhB/HdsoPW8k',
                      children: {},
                    },
                    '8mDxKylu': {
                      id: '8mDxKylu',
                      name: 'xGrim89LeghEWxy18e4RWrIFz',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'txt',
                      path: '2OZkKhxL/PdtJgIoq/sye04J7G/X2YzwYhB/8mDxKylu',
                    },
                    '6qONtttR': {
                      id: '6qONtttR',
                      name: 'I0M9y94M7LGFiFhlEOYjeMJpAOsufS4',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/sye04J7G/X2YzwYhB/6qONtttR',
                      children: {},
                    },
                  },
                },
                q5CSWlho: {
                  id: 'q5CSWlho',
                  name: 'ihnPBrmZG5vhJ3jkZqS6YyWa26ykG0C5',
                  protectionLevel: 'user',
                  type: 'folder',
                  path: '2OZkKhxL/PdtJgIoq/sye04J7G/q5CSWlho',
                  children: {
                    n8DZB1RC: {
                      id: 'n8DZB1RC',
                      name: 'OFoopuO3b1WYbxINutAAdx1liJFWHilGB',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/sye04J7G/q5CSWlho/n8DZB1RC',
                      children: {},
                    },
                    xwTB5Oym: {
                      id: 'xwTB5Oym',
                      name: 'F75VpUFZEeMIhj7QUoZRJH5vWZq',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'txt',
                      path: '2OZkKhxL/PdtJgIoq/sye04J7G/q5CSWlho/xwTB5Oym',
                    },
                    mFfHIrjI: {
                      id: 'mFfHIrjI',
                      name: 'Irnp9Fdzp2ADpIstXDicjjcZovHic',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'txt',
                      path: '2OZkKhxL/PdtJgIoq/sye04J7G/q5CSWlho/mFfHIrjI',
                    },
                    uX5UWwuf: {
                      id: 'uX5UWwuf',
                      name: 'TJhkocWSvnZ26tMWbLmIvfgvk2iLfb',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/sye04J7G/q5CSWlho/uX5UWwuf',
                      children: {},
                    },
                    x5to3oYy: {
                      id: 'x5to3oYy',
                      name: 'eEwNM2Fu4L9X2H4Eu5E9q0paX4AtLay',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'svg',
                      path: '2OZkKhxL/PdtJgIoq/sye04J7G/q5CSWlho/x5to3oYy',
                    },
                  },
                },
              },
            },
            pRvKPJDW: {
              id: 'pRvKPJDW',
              name: 'SEOtAcAiLVLuAzmLrcsPFxI0k51riTgVi6',
              protectionLevel: 'admin',
              type: 'file',
              extension: 'svg',
              path: '2OZkKhxL/PdtJgIoq/pRvKPJDW',
            },
            xcUw9D1r: {
              id: 'xcUw9D1r',
              name: '4ubYTz3mMQhdoZXdZFpBLlAt5Tgx',
              protectionLevel: 'admin',
              type: 'file',
              extension: 'svg',
              path: '2OZkKhxL/PdtJgIoq/xcUw9D1r',
            },
            '8Q0BGaIN': {
              id: '8Q0BGaIN',
              name: 'JNmLW9tNho4bgJg9XORMc5Vt6JlRL',
              protectionLevel: 'admin',
              type: 'folder',
              path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN',
              children: {
                F1u6aWN3: {
                  id: 'F1u6aWN3',
                  name: 'VnSu0BtYty1w5PtP2MpMWJGhfpbfWE',
                  protectionLevel: 'admin',
                  type: 'folder',
                  path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/F1u6aWN3',
                  children: {
                    pR0Iu5OX: {
                      id: 'pR0Iu5OX',
                      name: 'SWMuQT8ofaT14tutpwqsOrRq2N5sEo0rJTd',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'svg',
                      path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/F1u6aWN3/pR0Iu5OX',
                    },
                    lJhztHuD: {
                      id: 'lJhztHuD',
                      name: '4rt6sLlHhs4CbuUjzVpx2Kb9g',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/F1u6aWN3/lJhztHuD',
                      children: {},
                    },
                    cMv3XWHh: {
                      id: 'cMv3XWHh',
                      name: '2xjad2p8019o8SjmK7EfmK12Xv5Q1B',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/F1u6aWN3/cMv3XWHh',
                      children: {},
                    },
                    q61vDUBg: {
                      id: 'q61vDUBg',
                      name: 'utP8GejUYEbSbQ6tSjgKyQDWR81',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'txt',
                      path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/F1u6aWN3/q61vDUBg',
                    },
                    FGWyGwyq: {
                      id: 'FGWyGwyq',
                      name: 'mvmXJNFhH0mb0WFCBuMVvivG5N08gEfP',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/F1u6aWN3/FGWyGwyq',
                      children: {},
                    },
                  },
                },
                F1ptWo5S: {
                  id: 'F1ptWo5S',
                  name: 'JZFxBmzYrwEIavC5X9CHyGrobKRjU8',
                  protectionLevel: 'user',
                  type: 'file',
                  extension: 'txt',
                  path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/F1ptWo5S',
                },
                '1AuOXDLJ': {
                  id: '1AuOXDLJ',
                  name: 'BQNbKk2ABvloLQdMCBiuW8cvieDi',
                  protectionLevel: 'admin',
                  type: 'file',
                  extension: 'pdf',
                  path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/1AuOXDLJ',
                },
                '9JkXHJ6K': {
                  id: '9JkXHJ6K',
                  name: 'U77R3GHE0B8pVlrRwFH6rHnUT',
                  protectionLevel: 'user',
                  type: 'folder',
                  path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/9JkXHJ6K',
                  children: {
                    mFZpdfQw: {
                      id: 'mFZpdfQw',
                      name: 'uacN1zD3WusPclajdTWqUUWkG',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'pdf',
                      path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/9JkXHJ6K/mFZpdfQw',
                    },
                    THPzTDLX: {
                      id: 'THPzTDLX',
                      name: 'XwLaRVDltjAMTaJrUgVK5wx2Zf',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/9JkXHJ6K/THPzTDLX',
                      children: {},
                    },
                    XxAou2fA: {
                      id: 'XxAou2fA',
                      name: 'pdbcKyheaGXcCx3yxyTxpOFc4AwMIZL',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/9JkXHJ6K/XxAou2fA',
                      children: {},
                    },
                    jLG6HyuK: {
                      id: 'jLG6HyuK',
                      name: 'SXAu2ahQRQg41Oztj1mu3UcnE',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'pdf',
                      path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/9JkXHJ6K/jLG6HyuK',
                    },
                    X7jPJVZU: {
                      id: 'X7jPJVZU',
                      name: 'bXGUGvrS3TGO7gde0xo5EwCFFb',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'pdf',
                      path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/9JkXHJ6K/X7jPJVZU',
                    },
                  },
                },
                '5VqZprlW': {
                  id: '5VqZprlW',
                  name: 'hp7RGhO0QvM0u0zH2QDNhly3TS0CkLd',
                  protectionLevel: 'admin',
                  type: 'folder',
                  path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/5VqZprlW',
                  children: {
                    G0DnUfrh: {
                      id: 'G0DnUfrh',
                      name: 'CUwym9COBeEbJXZBEacnhcV3s4l',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/5VqZprlW/G0DnUfrh',
                      children: {},
                    },
                    REetsvpp: {
                      id: 'REetsvpp',
                      name: 'R6yZyMDV7Qf43IEWmkBTdY58ak6VqHs1',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'txt',
                      path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/5VqZprlW/REetsvpp',
                    },
                    IuGhIgQ5: {
                      id: 'IuGhIgQ5',
                      name: 'g242ZfYN8TJFb8WuMLjHtxQSH5w',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'txt',
                      path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/5VqZprlW/IuGhIgQ5',
                    },
                    N5zaYzWx: {
                      id: 'N5zaYzWx',
                      name: '3FWIGlzsTWyJutPhP5CshI5zi',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/5VqZprlW/N5zaYzWx',
                      children: {},
                    },
                    SQeh4hIO: {
                      id: 'SQeh4hIO',
                      name: 'lvpk8OLsWMxndyOt3dzcLDgm7M',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2OZkKhxL/PdtJgIoq/8Q0BGaIN/5VqZprlW/SQeh4hIO',
                      children: {},
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
    '2tFKv492': {
      id: '2tFKv492',
      name: 'JBILH0oeijuinBhGQGMXMad0yM1BxQnvBC',
      protectionLevel: 'admin',
      type: 'folder',
      path: '2tFKv492',
      children: {
        Go1jy5V6: {
          id: 'Go1jy5V6',
          name: 'V885LGw6FeGduumINSZbxgOaPuVuW',
          protectionLevel: 'admin',
          type: 'file',
          extension: 'txt',
          path: '2tFKv492/Go1jy5V6',
        },
        pkgFiWdR: {
          id: 'pkgFiWdR',
          name: 'xiZmQODUGdgZVCP98eXATws1yQ4YIext4yW',
          protectionLevel: 'admin',
          type: 'file',
          extension: 'txt',
          path: '2tFKv492/pkgFiWdR',
        },
        rksbTktr: {
          id: 'rksbTktr',
          name: 'BYzs7CeTQ8Oci5fbORDQozAO6NZe',
          protectionLevel: 'admin',
          type: 'folder',
          path: '2tFKv492/rksbTktr',
          children: {
            H7bdoVTb: {
              id: 'H7bdoVTb',
              name: 'uWkQOZfTm1escKwRDJLoTO6XYOQClrCWh',
              protectionLevel: 'user',
              type: 'folder',
              path: '2tFKv492/rksbTktr/H7bdoVTb',
              children: {
                kvUgNchI: {
                  id: 'kvUgNchI',
                  name: 'WVvITB1K4k6IYlnFCb5GUHfusOaYb',
                  protectionLevel: 'user',
                  type: 'file',
                  extension: 'txt',
                  path: '2tFKv492/rksbTktr/H7bdoVTb/kvUgNchI',
                },
                Ql2hXPA6: {
                  id: 'Ql2hXPA6',
                  name: '1s3pklagMBfXs1xnN9y0goW1XvpwCm1IJeu',
                  protectionLevel: 'admin',
                  type: 'folder',
                  path: '2tFKv492/rksbTktr/H7bdoVTb/Ql2hXPA6',
                  children: {
                    tKLPo0rS: {
                      id: 'tKLPo0rS',
                      name: '2dMgToTbpOg4u5EOvRoZXGV6wLjH',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'txt',
                      path: '2tFKv492/rksbTktr/H7bdoVTb/Ql2hXPA6/tKLPo0rS',
                    },
                    CXlIC5xJ: {
                      id: 'CXlIC5xJ',
                      name: 'J7URnU1LLbMyWc6iov8IKajIFr',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'txt',
                      path: '2tFKv492/rksbTktr/H7bdoVTb/Ql2hXPA6/CXlIC5xJ',
                    },
                    dSdrmMW7: {
                      id: 'dSdrmMW7',
                      name: '08HX8sJdH24MRw1K7vBrwAhqtK1J8F',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2tFKv492/rksbTktr/H7bdoVTb/Ql2hXPA6/dSdrmMW7',
                      children: {},
                    },
                    mAf2dEpS: {
                      id: 'mAf2dEpS',
                      name: 'sLxIggEuGbKD112s5h1LrXLMDoyx9PB4',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2tFKv492/rksbTktr/H7bdoVTb/Ql2hXPA6/mAf2dEpS',
                      children: {},
                    },
                    hlNOUohl: {
                      id: 'hlNOUohl',
                      name: 'I9jPGJZb6KyPnIONATSYEIv1IFaxnT',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'pdf',
                      path: '2tFKv492/rksbTktr/H7bdoVTb/Ql2hXPA6/hlNOUohl',
                    },
                  },
                },
                Ehom1axB: {
                  id: 'Ehom1axB',
                  name: 'JOVFfM2gpUBGCW33Ng2CSG1gpy',
                  protectionLevel: 'admin',
                  type: 'file',
                  extension: 'pdf',
                  path: '2tFKv492/rksbTktr/H7bdoVTb/Ehom1axB',
                },
                E5i6paLe: {
                  id: 'E5i6paLe',
                  name: 'sD17VNlWzxsQKPzeqMdEqmruVrpIL6mYAX',
                  protectionLevel: 'user',
                  type: 'file',
                  extension: 'pdf',
                  path: '2tFKv492/rksbTktr/H7bdoVTb/E5i6paLe',
                },
                '2TSIdlZ3': {
                  id: '2TSIdlZ3',
                  name: 'neOsIVlTddzIXGfnkbjaWV3cv',
                  protectionLevel: 'user',
                  type: 'file',
                  extension: 'txt',
                  path: '2tFKv492/rksbTktr/H7bdoVTb/2TSIdlZ3',
                },
              },
            },
            '3WMpMm32': {
              id: '3WMpMm32',
              name: 'zwVMXpVUe85MDH65jQdJ585Jaz2VNpUtu3S',
              protectionLevel: 'admin',
              type: 'file',
              extension: 'txt',
              path: '2tFKv492/rksbTktr/3WMpMm32',
            },
            nf5nOGNp: {
              id: 'nf5nOGNp',
              name: 'SXPZjGKgUvnNfpfDp3tC3iYy4gUpI',
              protectionLevel: 'user',
              type: 'folder',
              path: '2tFKv492/rksbTktr/nf5nOGNp',
              children: {
                fLVaOtiU: {
                  id: 'fLVaOtiU',
                  name: 'U6ygar0yP5q0DlXlwUq6OC6KytMKuN9sIt2',
                  protectionLevel: 'user',
                  type: 'file',
                  extension: 'txt',
                  path: '2tFKv492/rksbTktr/nf5nOGNp/fLVaOtiU',
                },
                '6qiN0fnN': {
                  id: '6qiN0fnN',
                  name: 'NoNsvi5GjNv0evdB8stFT6ARmUNdYwr5SzY',
                  protectionLevel: 'admin',
                  type: 'file',
                  extension: 'txt',
                  path: '2tFKv492/rksbTktr/nf5nOGNp/6qiN0fnN',
                },
                cWPK8sez: {
                  id: 'cWPK8sez',
                  name: '7cJIDE32u2x8pzFvPxJyysD5E',
                  protectionLevel: 'user',
                  type: 'folder',
                  path: '2tFKv492/rksbTktr/nf5nOGNp/cWPK8sez',
                  children: {
                    kGoJNJ3k: {
                      id: 'kGoJNJ3k',
                      name: 'Jz9BHmPRPAT5FYKMEsRCpYsE9',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'pdf',
                      path: '2tFKv492/rksbTktr/nf5nOGNp/cWPK8sez/kGoJNJ3k',
                    },
                    T9M5hb4r: {
                      id: 'T9M5hb4r',
                      name: 'K32JpEWFFtyZWGpHgC26MmUox9',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2tFKv492/rksbTktr/nf5nOGNp/cWPK8sez/T9M5hb4r',
                      children: {},
                    },
                    v5TPKhMD: {
                      id: 'v5TPKhMD',
                      name: '7jOiMvWIE1rnSwS0MkSo2FP24AzYFwSTw',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'pdf',
                      path: '2tFKv492/rksbTktr/nf5nOGNp/cWPK8sez/v5TPKhMD',
                    },
                    '1reTDcWf': {
                      id: '1reTDcWf',
                      name: 'gl18GwlfMGRwKaMfi9GhwVbxRuFVhif9',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'pdf',
                      path: '2tFKv492/rksbTktr/nf5nOGNp/cWPK8sez/1reTDcWf',
                    },
                    '3BB9l0z4': {
                      id: '3BB9l0z4',
                      name: 'ZbONPsvK0FYeVO5Tu9thjvd8cWKhUGOZ',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2tFKv492/rksbTktr/nf5nOGNp/cWPK8sez/3BB9l0z4',
                      children: {},
                    },
                  },
                },
                '9AwfaIR2': {
                  id: '9AwfaIR2',
                  name: 'AbUS8cX0coJjRN2I22mgeZnVTC',
                  protectionLevel: 'user',
                  type: 'file',
                  extension: 'txt',
                  path: '2tFKv492/rksbTktr/nf5nOGNp/9AwfaIR2',
                },
                Miy4crIa: {
                  id: 'Miy4crIa',
                  name: '8rUYiW1ugkbanjFdMTiZAyqGzn0R0w',
                  protectionLevel: 'admin',
                  type: 'file',
                  extension: 'txt',
                  path: '2tFKv492/rksbTktr/nf5nOGNp/Miy4crIa',
                },
              },
            },
            UjAEjCFV: {
              id: 'UjAEjCFV',
              name: 'UPLT5HOdiAx3sGjEAwP4CWhLb54UMwKM',
              protectionLevel: 'admin',
              type: 'file',
              extension: 'txt',
              path: '2tFKv492/rksbTktr/UjAEjCFV',
            },
            Abhw78uA: {
              id: 'Abhw78uA',
              name: 'epro2snaKF4AMzbyxSY4AABBHSrdvnvsc1',
              protectionLevel: 'user',
              type: 'folder',
              path: '2tFKv492/rksbTktr/Abhw78uA',
              children: {
                DgdMJKTt: {
                  id: 'DgdMJKTt',
                  name: 'J8qj3r0UaP6wKa88WOLKsWLJKL6FpzE',
                  protectionLevel: 'admin',
                  type: 'file',
                  extension: 'txt',
                  path: '2tFKv492/rksbTktr/Abhw78uA/DgdMJKTt',
                },
                pKwouJcx: {
                  id: 'pKwouJcx',
                  name: 'ZkjafGOGgwb9ESP5CaaVq7YRhs6u6LGGa',
                  protectionLevel: 'admin',
                  type: 'folder',
                  path: '2tFKv492/rksbTktr/Abhw78uA/pKwouJcx',
                  children: {
                    '9ICTERar': {
                      id: '9ICTERar',
                      name: 'Izw2YtSXSw4BzGd8ReXRtqqtFgjYcSs9',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'txt',
                      path: '2tFKv492/rksbTktr/Abhw78uA/pKwouJcx/9ICTERar',
                    },
                    '54BaNl5g': {
                      id: '54BaNl5g',
                      name: '8deG3e302056azOFYVby3KLWiT5I',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2tFKv492/rksbTktr/Abhw78uA/pKwouJcx/54BaNl5g',
                      children: {},
                    },
                    QEocv7Tv: {
                      id: 'QEocv7Tv',
                      name: 'xZWo2Ywxi93x6FqWOk5QdarHh15lud',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2tFKv492/rksbTktr/Abhw78uA/pKwouJcx/QEocv7Tv',
                      children: {},
                    },
                    '6A5yRieX': {
                      id: '6A5yRieX',
                      name: 'Gn1lYoM8cs8v4kQU692ZR8ONycQZdS',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2tFKv492/rksbTktr/Abhw78uA/pKwouJcx/6A5yRieX',
                      children: {},
                    },
                    SpCbQEDd: {
                      id: 'SpCbQEDd',
                      name: 'fIw2nakvUPynKKmkWM1lETQSjEhs',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2tFKv492/rksbTktr/Abhw78uA/pKwouJcx/SpCbQEDd',
                      children: {},
                    },
                  },
                },
                Vv42yIww: {
                  id: 'Vv42yIww',
                  name: 'rMeFcbY7i4gfzBUjGSezblbfxIsMbR',
                  protectionLevel: 'user',
                  type: 'folder',
                  path: '2tFKv492/rksbTktr/Abhw78uA/Vv42yIww',
                  children: {
                    Zhu2SGMZ: {
                      id: 'Zhu2SGMZ',
                      name: '51mht5jMX9SUZFVRPQ7mh1A2Wt1Y',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'txt',
                      path: '2tFKv492/rksbTktr/Abhw78uA/Vv42yIww/Zhu2SGMZ',
                    },
                    nHQ72OvK: {
                      id: 'nHQ72OvK',
                      name: 'UZlFD6w2ACykdpe7DKebHhNhgdZMcin9YH',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'pdf',
                      path: '2tFKv492/rksbTktr/Abhw78uA/Vv42yIww/nHQ72OvK',
                    },
                    DmLHwdyr: {
                      id: 'DmLHwdyr',
                      name: '0amad1ZM7KU6A5q24Dczl3EqvUQZSD',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'pdf',
                      path: '2tFKv492/rksbTktr/Abhw78uA/Vv42yIww/DmLHwdyr',
                    },
                    J0XAiYp9: {
                      id: 'J0XAiYp9',
                      name: 'Nkc5LwSpHLXNHJ7woGsmA23L7',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2tFKv492/rksbTktr/Abhw78uA/Vv42yIww/J0XAiYp9',
                      children: {},
                    },
                    '4JGsQcYE': {
                      id: '4JGsQcYE',
                      name: '87mImUpeIJToparXYrjwPsjpCptu',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2tFKv492/rksbTktr/Abhw78uA/Vv42yIww/4JGsQcYE',
                      children: {},
                    },
                  },
                },
                '1zel4bHT': {
                  id: '1zel4bHT',
                  name: 'epHh0ohc2NVfcGbLiLhUAnqQb',
                  protectionLevel: 'admin',
                  type: 'file',
                  extension: 'pdf',
                  path: '2tFKv492/rksbTktr/Abhw78uA/1zel4bHT',
                },
                QSaTGqJW: {
                  id: 'QSaTGqJW',
                  name: 'gsi9UJ8v8VKCre66sL86Ha7b2JGxDGYoPom',
                  protectionLevel: 'user',
                  type: 'folder',
                  path: '2tFKv492/rksbTktr/Abhw78uA/QSaTGqJW',
                  children: {
                    qdg9Ytzo: {
                      id: 'qdg9Ytzo',
                      name: 'ztggZgoF3jagFBZmhie2hJccwy6pJOl4yu7',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'pdf',
                      path: '2tFKv492/rksbTktr/Abhw78uA/QSaTGqJW/qdg9Ytzo',
                    },
                    uwbCa76L: {
                      id: 'uwbCa76L',
                      name: 'QuAyLMCeRsUvMTMlmqnVgW6vgifJrnw3',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2tFKv492/rksbTktr/Abhw78uA/QSaTGqJW/uwbCa76L',
                      children: {},
                    },
                    c18bbiSk: {
                      id: 'c18bbiSk',
                      name: 'iApNZ0hTGHOWuEKxsTRX7yANaM9',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'pdf',
                      path: '2tFKv492/rksbTktr/Abhw78uA/QSaTGqJW/c18bbiSk',
                    },
                    gtBAaNeC: {
                      id: 'gtBAaNeC',
                      name: 'tVTRARgEnuTIMKGJmwTrrGB3CkZZ',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'pdf',
                      path: '2tFKv492/rksbTktr/Abhw78uA/QSaTGqJW/gtBAaNeC',
                    },
                    HXEI9N2n: {
                      id: 'HXEI9N2n',
                      name: 'qp1fnNmGWuYsuoGUSwGYkXavg9UyNC8itv',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2tFKv492/rksbTktr/Abhw78uA/QSaTGqJW/HXEI9N2n',
                      children: {},
                    },
                  },
                },
              },
            },
          },
        },
        yxuA3na8: {
          id: 'yxuA3na8',
          name: 'uSEZHyWKjzOSrukjpezQGhVgeqRhsuj6R',
          protectionLevel: 'admin',
          type: 'file',
          extension: 'pdf',
          path: '2tFKv492/yxuA3na8',
        },
        vTECffXo: {
          id: 'vTECffXo',
          name: '0Duyibkn0DXfas0b6kmGe8Mu3XojG',
          protectionLevel: 'user',
          type: 'folder',
          path: '2tFKv492/vTECffXo',
          children: {
            xFUO4q9u: {
              id: 'xFUO4q9u',
              name: 'c5FebLasW68Uf4z0y7EAy2v5rRDreyR',
              protectionLevel: 'user',
              type: 'file',
              extension: 'txt',
              path: '2tFKv492/vTECffXo/xFUO4q9u',
            },
            tCS4IpvC: {
              id: 'tCS4IpvC',
              name: 'HAgyMtOjvBMA0fNOZjZcIyCXdflWF',
              protectionLevel: 'user',
              type: 'file',
              extension: 'txt',
              path: '2tFKv492/vTECffXo/tCS4IpvC',
            },
            '7r95dBOn': {
              id: '7r95dBOn',
              name: '2MTzkutBHFaOU0IYhVvuOTJCXCxFtNEj2O',
              protectionLevel: 'admin',
              type: 'file',
              extension: 'txt',
              path: '2tFKv492/vTECffXo/7r95dBOn',
            },
            XHMaaR1N: {
              id: 'XHMaaR1N',
              name: 'xVke0Z0tJEXCgDKeyMEdWp6BsxkaZ4',
              protectionLevel: 'user',
              type: 'folder',
              path: '2tFKv492/vTECffXo/XHMaaR1N',
              children: {
                '0saMe5Pb': {
                  id: '0saMe5Pb',
                  name: 'eGkaVXSOAPLWsckX14R8ZPHacM',
                  protectionLevel: 'user',
                  type: 'folder',
                  path: '2tFKv492/vTECffXo/XHMaaR1N/0saMe5Pb',
                  children: {
                    RfXsUruo: {
                      id: 'RfXsUruo',
                      name: 'jHjJugf0JEAaeMHFjC9H3SWNJ29Yja',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'txt',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/0saMe5Pb/RfXsUruo',
                    },
                    qUqzu4uU: {
                      id: 'qUqzu4uU',
                      name: 'N1QJor6wcvieHHzC5iGnTmmuNYSk5jww1cH',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/0saMe5Pb/qUqzu4uU',
                      children: {},
                    },
                    zydR3L5F: {
                      id: 'zydR3L5F',
                      name: 'BXgVa1S0njQHgOsgLhbaVIqGjsodjQ0XIL',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'pdf',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/0saMe5Pb/zydR3L5F',
                    },
                    RNnY8AVp: {
                      id: 'RNnY8AVp',
                      name: 'Q5ukRBCEzj980FLAGsuHgBwYjjMheFCu',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/0saMe5Pb/RNnY8AVp',
                      children: {},
                    },
                    '89wxiEVZ': {
                      id: '89wxiEVZ',
                      name: 'BULYr59fsckJRvh8KKrybxaxhplbIQTaaK8',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'pdf',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/0saMe5Pb/89wxiEVZ',
                    },
                  },
                },
                MIfgvaIS: {
                  id: 'MIfgvaIS',
                  name: '3r9UkRCRQUBlSWxhIuZnRwV9kE',
                  protectionLevel: 'user',
                  type: 'file',
                  extension: 'pdf',
                  path: '2tFKv492/vTECffXo/XHMaaR1N/MIfgvaIS',
                },
                N05MwQl3: {
                  id: 'N05MwQl3',
                  name: 'nNpvyfqf9QgK6y1bzc5tbRa0FsRb53',
                  protectionLevel: 'user',
                  type: 'folder',
                  path: '2tFKv492/vTECffXo/XHMaaR1N/N05MwQl3',
                  children: {
                    jq3bCi3Z: {
                      id: 'jq3bCi3Z',
                      name: 'GdDaI9TluxRSykUPrcf5dYa0oh2GbBOn',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'pdf',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/N05MwQl3/jq3bCi3Z',
                    },
                    VShSvKBJ: {
                      id: 'VShSvKBJ',
                      name: '2XT1q78GG1AN0w6MXC2jHmTvSzX',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/N05MwQl3/VShSvKBJ',
                      children: {},
                    },
                    gUzXNVKf: {
                      id: 'gUzXNVKf',
                      name: 'cXox2fODurEXCZs0vvGEmYz80GgE',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/N05MwQl3/gUzXNVKf',
                      children: {},
                    },
                    zl3RSLiJ: {
                      id: 'zl3RSLiJ',
                      name: 'YLGxmU4uzDV5mFkR9rQIx6bann9u',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'txt',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/N05MwQl3/zl3RSLiJ',
                    },
                    RoQzrOem: {
                      id: 'RoQzrOem',
                      name: 'Fu0xtBv35Yf50Lm4FpWx5mLSe5TR8Q',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'txt',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/N05MwQl3/RoQzrOem',
                    },
                  },
                },
                fjSDIJGy: {
                  id: 'fjSDIJGy',
                  name: '5cqkShERGzEyTMf9KOqyqoSmqJ3',
                  protectionLevel: 'user',
                  type: 'folder',
                  path: '2tFKv492/vTECffXo/XHMaaR1N/fjSDIJGy',
                  children: {
                    zX21Phai: {
                      id: 'zX21Phai',
                      name: 'vKaTjQ66DUiIAK3UiXzNa0mUHU1gqqUHet',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/fjSDIJGy/zX21Phai',
                      children: {},
                    },
                    '1Ntxey1f': {
                      id: '1Ntxey1f',
                      name: 'iJYuxERlaaAWvAvUWECeylQnjdo',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/fjSDIJGy/1Ntxey1f',
                      children: {},
                    },
                    GNCzuw6b: {
                      id: 'GNCzuw6b',
                      name: 'OmEkhVnw3JjZyOEaQhfZeDmKvPWf2YhezOA',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'txt',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/fjSDIJGy/GNCzuw6b',
                    },
                    VsEJxwkX: {
                      id: 'VsEJxwkX',
                      name: 'y1NjoG9LwyimRkDH5uidzTTOK2KUmHj',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/fjSDIJGy/VsEJxwkX',
                      children: {},
                    },
                    oNnJeaVF: {
                      id: 'oNnJeaVF',
                      name: 'tU1r0ZNy7tUTBfuxjknszSJKDfGF0bZlX7K',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'txt',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/fjSDIJGy/oNnJeaVF',
                    },
                  },
                },
                CKlD926j: {
                  id: 'CKlD926j',
                  name: 'jIwdJZt7FUKQoK7b17OwUHS9yC',
                  protectionLevel: 'admin',
                  type: 'folder',
                  path: '2tFKv492/vTECffXo/XHMaaR1N/CKlD926j',
                  children: {
                    ypxDB2xC: {
                      id: 'ypxDB2xC',
                      name: 'bfIsQKuzckGbRETZsH0czc3p0SE1BxqtL',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/CKlD926j/ypxDB2xC',
                      children: {},
                    },
                    E7mLdzdP: {
                      id: 'E7mLdzdP',
                      name: 'OFnpACMwYYx1Kpg7hvKLVqdaiWkAU',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/CKlD926j/E7mLdzdP',
                      children: {},
                    },
                    xuWcGaBy: {
                      id: 'xuWcGaBy',
                      name: 'ZGTFen7rY9WTgoLIsfTywA6Kdw',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'txt',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/CKlD926j/xuWcGaBy',
                    },
                    ikMQRnJw: {
                      id: 'ikMQRnJw',
                      name: 'gxpUXmHh4zVcnvYHrFT1kuSygzhItQAkC',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/CKlD926j/ikMQRnJw',
                      children: {},
                    },
                    '3tqnCVN2': {
                      id: '3tqnCVN2',
                      name: '4JsgondCwVLllXadXOQdKS1t2ZcRkS4A',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/XHMaaR1N/CKlD926j/3tqnCVN2',
                      children: {},
                    },
                  },
                },
              },
            },
            t0BRkhXS: {
              id: 't0BRkhXS',
              name: '7cQFRuKZmgIJc4AtO6rGF5moqAdQnwsXxFy',
              protectionLevel: 'user',
              type: 'folder',
              path: '2tFKv492/vTECffXo/t0BRkhXS',
              children: {
                nOfZsFbq: {
                  id: 'nOfZsFbq',
                  name: '5Mu8EzBEA25aquzFXpLiJiIGnuX',
                  protectionLevel: 'user',
                  type: 'folder',
                  path: '2tFKv492/vTECffXo/t0BRkhXS/nOfZsFbq',
                  children: {
                    vwOYcBvg: {
                      id: 'vwOYcBvg',
                      name: 'phFp7WPlQoBql4Gge35NbhUGrbwaEUc',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/t0BRkhXS/nOfZsFbq/vwOYcBvg',
                      children: {},
                    },
                    H95OY8IC: {
                      id: 'H95OY8IC',
                      name: 'qsKlKs4fi5mJUblTRTUdi2TT5d5zSWD',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/t0BRkhXS/nOfZsFbq/H95OY8IC',
                      children: {},
                    },
                    L3BSF0H5: {
                      id: 'L3BSF0H5',
                      name: '6tKy7FguQyU9xqinRjyGrRBEe',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'txt',
                      path: '2tFKv492/vTECffXo/t0BRkhXS/nOfZsFbq/L3BSF0H5',
                    },
                    PqBJfHBJ: {
                      id: 'PqBJfHBJ',
                      name: 'ZSEUFzWthSB8klisSa4PEpj6InKdPSe13o',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'svg',
                      path: '2tFKv492/vTECffXo/t0BRkhXS/nOfZsFbq/PqBJfHBJ',
                    },
                    H7sMThhB: {
                      id: 'H7sMThhB',
                      name: 'je2cbGQm6xLzH3NcxoNHvmYNl0y0',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'svg',
                      path: '2tFKv492/vTECffXo/t0BRkhXS/nOfZsFbq/H7sMThhB',
                    },
                  },
                },
                Bjdsg90M: {
                  id: 'Bjdsg90M',
                  name: 'dxUbt0rTX6I21vLx6Y0DqeZzphSdmk',
                  protectionLevel: 'user',
                  type: 'file',
                  extension: 'svg',
                  path: '2tFKv492/vTECffXo/t0BRkhXS/Bjdsg90M',
                },
                '7qk18eGg': {
                  id: '7qk18eGg',
                  name: 'mb8zoWxemlov0kRgEZoq8n9v6',
                  protectionLevel: 'user',
                  type: 'folder',
                  path: '2tFKv492/vTECffXo/t0BRkhXS/7qk18eGg',
                  children: {
                    u4jexWQi: {
                      id: 'u4jexWQi',
                      name: 'jqyXyTyDq1Vm91MoH3H7Z1eZOQ7dW',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'svg',
                      path: '2tFKv492/vTECffXo/t0BRkhXS/7qk18eGg/u4jexWQi',
                    },
                    SN69zN1q: {
                      id: 'SN69zN1q',
                      name: 'ItQxdmIT3Kc65AFLhhZktHMfsQKy7ncBBI7',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'txt',
                      path: '2tFKv492/vTECffXo/t0BRkhXS/7qk18eGg/SN69zN1q',
                    },
                    WwGanjIi: {
                      id: 'WwGanjIi',
                      name: 'Wfi4a4lnpzYDY7sTw8Xdko80Ru5smH2U',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/t0BRkhXS/7qk18eGg/WwGanjIi',
                      children: {},
                    },
                    lqFmuPuw: {
                      id: 'lqFmuPuw',
                      name: '2dNyPDFGGEpb5lAXpDnNIVmEkq8xV',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/t0BRkhXS/7qk18eGg/lqFmuPuw',
                      children: {},
                    },
                    bD7VmBgu: {
                      id: 'bD7VmBgu',
                      name: 'LOnwuhcFVOGW59aKHb84Kbd6Vln8',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'txt',
                      path: '2tFKv492/vTECffXo/t0BRkhXS/7qk18eGg/bD7VmBgu',
                    },
                  },
                },
                Qmaw8tur: {
                  id: 'Qmaw8tur',
                  name: '9ObkuO2KDgGxLsuKjanr3zbVVlpZnFwhG5',
                  protectionLevel: 'admin',
                  type: 'file',
                  extension: 'txt',
                  path: '2tFKv492/vTECffXo/t0BRkhXS/Qmaw8tur',
                },
                '931ykEHe': {
                  id: '931ykEHe',
                  name: 't49ZKnHETMEpic7BfKTmA4D2bsT',
                  protectionLevel: 'admin',
                  type: 'folder',
                  path: '2tFKv492/vTECffXo/t0BRkhXS/931ykEHe',
                  children: {
                    m6d5saNm: {
                      id: 'm6d5saNm',
                      name: 'oiw1aVZ9JEaffxjcOTSH3rwJUWwNQbtqy',
                      protectionLevel: 'admin',
                      type: 'file',
                      extension: 'txt',
                      path: '2tFKv492/vTECffXo/t0BRkhXS/931ykEHe/m6d5saNm',
                    },
                    DFiNOiml: {
                      id: 'DFiNOiml',
                      name: 'OfSg9MfPkJwIhdDCPOj72qF1ywDh',
                      protectionLevel: 'admin',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/t0BRkhXS/931ykEHe/DFiNOiml',
                      children: {},
                    },
                    qYKCRqRN: {
                      id: 'qYKCRqRN',
                      name: 'LwVc4plBH5J6ybLafUIFUV58TcFHo93NQ5',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/t0BRkhXS/931ykEHe/qYKCRqRN',
                      children: {},
                    },
                    cZRqIExW: {
                      id: 'cZRqIExW',
                      name: 'WDWBHS9wyMMHCNxPIbetM9DTsTKckAH',
                      protectionLevel: 'user',
                      type: 'file',
                      extension: 'txt',
                      path: '2tFKv492/vTECffXo/t0BRkhXS/931ykEHe/cZRqIExW',
                    },
                    HIw9juay: {
                      id: 'HIw9juay',
                      name: 'IaT4BQfSCVju8iTW1oFgQK9a0Jbq64fm2',
                      protectionLevel: 'user',
                      type: 'folder',
                      path: '2tFKv492/vTECffXo/t0BRkhXS/931ykEHe/HIw9juay',
                      children: {},
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
    '4fXztf8h': {
      id: '4fXztf8h',
      name: 'tYU5rft2dUfQWvI5oWKylSPEixzC',
      protectionLevel: 'admin',
      type: 'file',
      extension: 'txt',
      path: '4fXztf8h',
    },
    '3sdXztf8h': {
      id: '3sdXztf8h',
      name: 'sadsasad21312423asd123',
      protectionLevel: 'admin',
      type: 'file',
      extension: 'txt',
      path: '3sdXztf8h',
    },
  },
};
